# Generated by Django 4.1.4 on 2023-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="visit_date",
            field=models.DateField(unique_for_date="visit_date"),
        ),
    ]
