# Generated by Django 4.1.4 on 2023-05-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("imweb_price", models.PositiveIntegerField()),
                ("imweb_deliv_price", models.PositiveIntegerField()),
                ("product_cost", models.PositiveIntegerField()),
                ("product_profit", models.IntegerField()),
                ("facebook_ad_expense_krw", models.PositiveIntegerField()),
                ("expense", models.PositiveIntegerField()),
                ("operating_profit", models.IntegerField()),
                ("imweb_nomal_order_counter", models.PositiveIntegerField()),
                ("imweb_npay_order_counter", models.PositiveIntegerField()),
                ("imweb_count", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brands.brand"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
