# Generated by Django 4.1.4 on 2023-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="expense",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="facebook_ad_expense_krw",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="operating_profit",
            field=models.FloatField(),
        ),
    ]
