# Generated by Django 4.1.4 on 2023-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
