# Generated by Django 4.1.4 on 2023-05-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("imweb_price", models.IntegerField()),
                ("imweb_deliv_price", models.IntegerField()),
                ("product_cost", models.IntegerField()),
                ("product_profit", models.IntegerField()),
                ("facebook_ad_expense_krw", models.IntegerField()),
                ("expense", models.IntegerField()),
                ("operating_profit", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brands.brand"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
