# Generated by Django 4.1.4 on 2023-05-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0003_alter_data_expense_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Data",
            new_name="BrandData",
        ),
    ]
