# Generated by Django 4.1.4 on 2023-05-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0004_rename_data_branddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseByHand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=150)),
                ("expense_by_hand", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brands.brand"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
