# Generated by Django 4.1.4 on 2023-03-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_initial"),
        ("pages", "0002_alter_page_page_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="brands.brand",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="page_date",
            field=models.DateField(),
        ),
    ]
