# Generated by Django 4.1.4 on 2023-03-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_initial"),
        ("pages", "0004_alter_page_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="brands.brand"
            ),
        ),
    ]
