# Generated by Django 4.1.4 on 2023-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_page_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_date",
            field=models.DateField(unique_for_date=True),
        ),
    ]
