# Generated by Django 4.1.4 on 2023-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_page_page_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_date",
            field=models.DateField(unique_for_date="page_date"),
        ),
    ]
