# Generated by Django 4.1.4 on 2023-01-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertising",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_id", models.CharField(max_length=150)),
                ("campaign_name", models.CharField(max_length=150)),
                ("reach", models.CharField(max_length=150)),
                ("impressions", models.CharField(max_length=150)),
                ("frequency", models.CharField(max_length=150)),
                ("spend", models.CharField(max_length=150)),
                ("cpm", models.CharField(max_length=150)),
                ("purchase_roas", models.CharField(max_length=150)),
                ("website_ctr", models.CharField(max_length=150)),
                ("cost_per_unique_inline_link_click", models.CharField(max_length=150)),
                ("purchase", models.CharField(max_length=150)),
                ("landing_page_view", models.CharField(max_length=150)),
                ("link_click", models.CharField(max_length=150)),
                ("ad_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
