# Generated by Django 4.1.4 on 2023-03-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("url", models.URLField()),
                ("api_key", models.CharField(blank=True, max_length=150, null=True)),
                ("secret_key", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "ad_account_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sale_site", "Sale"),
                            ("advertising_site", "Advertising"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brands.brand"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
