# Generated by Django 4.1.4 on 2023-01-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="kind",
            field=models.CharField(
                choices=[("sale_site", "Sale"), ("advertising_site", "Advertising")],
                max_length=20,
                null=True,
            ),
        ),
    ]
