# Generated by Django 4.1.4 on 2023-04-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
