# Generated by Django 4.1.4 on 2023-01-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_site_api_key_site_secret_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="ad_account_id",
            field=models.CharField(default="", max_length=150),
        ),
    ]
