# Generated by Django 4.1.4 on 2023-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_alter_site_ad_account_id_alter_site_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="ad_account_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="api_key",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="secret_key",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
