# Generated by Django 4.1.4 on 2023-01-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="order_no",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="order_time",
            field=models.DateTimeField(null=True),
        ),
    ]
