# Generated by Django 4.1.4 on 2023-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdata",
            name="imweb_deliv_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productdata",
            name="imweb_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
