# Generated by Django 4.1.4 on 2023-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_options_gift_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="english_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
