# Generated by Django 4.1.4 on 2023-02-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_gift_quantity_product_logistic_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="options",
            name="gift_quantity",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="gift_quantity",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
