# Generated by Django 4.1.4 on 2023-02-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_options_gift_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="english_name",
        ),
    ]
