# Generated by Django 4.1.4 on 2023-02-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_english_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="options",
            name="cost",
        ),
    ]
