# Generated by Django 4.1.4 on 2023-02-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_options_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="options",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
