# Generated by Django 4.1.4 on 2023-03-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
